version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:45"
      timezone: "America/Chicago"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:45"
      timezone: "America/Chicago"