---
name: Code Quality Scan
on:
  push:
  pull_request:
    branches:
    - main

jobs:
  code-quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Dependencies
      run: pip3 install -r requirements.txt

    - name: Lint Codebase
      uses: github/super-linter/slim@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_MARKDOWN: true
        VALIDATE_PYTHON: true
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_YAML: true

    - name: Unit Tests
      run: python -m unittest discover tests "test*.py"
