name: Pulumi Gardener Kubernetes Shoot Cluster CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9","3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: pip3 install -r requirements.txt
    - name: Lint Codebase
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_PYTHON: true
    - name: Unit Tests
      run: python -m unittest discover tests "test*.py"

      


